Repository openwisp/openwisp-wifi-login-pages, pull requests merged in 2021-09, with the labels that each got.

#400 [refactor] Avoid duplicated send-cookie logic in server
  server/controllers/obtain-token-controller.js
  server/controllers/registration-controller.js
  server/utils/send-cookies.js
Labels: enhancement

#201 [bug] Fixed unique key props error when no links #169
  client/components/footer/footer.js
  client/components/header/header.js
Labels: bug

#405 [feature] Added pre-payment page
  client/components/login/login.js
  client/components/login/login.test.js
  client/components/organization-wrapper/__snapshots__/organization-wrapper.test.js.snap
  client/components/organization-wrapper/organization-wrapper.js
  client/components/organization-wrapper/organization-wrapper.test.js
  client/components/payment-status/__snapshots__/payment-status.test.js.snap
  client/components/payment-status/index.js
  client/components/payment-status/payment-status.js
  client/components/payment-status/payment-status.test.js
  client/components/registration/registration.js
  client/components/registration/subscriptions.test.js
  client/index.css
  client/utils/redirect-to-payment.js
  client/utils/utils.test.js
  i18n/de.po
  i18n/en.po
  i18n/fur.po
  i18n/it.po
  i18n/sl.po
Labels: enhancement

#413 [fix/change] Fixed hanging logout + force logout after payment #410
  browser-test/mobile-phone-change.test.js
  browser-test/mobile-verfication.test.js
  browser-test/utils.js
  client/actions/actions.test.js
  client/components/login/login.js
  client/components/organization-wrapper/lazy-import.js
  client/components/organization-wrapper/organization-wrapper.js
  client/components/organization-wrapper/organization-wrapper.test.js
  client/components/status/status.js
  client/components/status/status.test.js
  client/reducers/organization.js
  client/reducers/reducers.test.js
  client/utils/utils.test.js
  i18n/de.po
  i18n/en.po
  i18n/fur.po
  i18n/it.po
  i18n/ru.po
  i18n/sl.po
Labels: bug, enhancement
