Repository openwisp/openwisp-wifi-login-pages, pull requests merged in 2025-07, with the labels that each got.

#901 [fix] Fixed upgrade button and limit exceeded message not rendering
  client/components/status/__snapshots__/status.test.js.snap
  client/components/status/status.js
  client/components/status/status.test.js
Labels: bug

#903 [chores:i18n] Updated translations
  i18n/de.po
  i18n/en.po
  i18n/es.po
  i18n/fur.po
  i18n/it.po
  i18n/ru.po
  i18n/sl.po
Labels: enhancement

#899 [deps] Upgrade dependencies and react to v17 #854
  .eslintrc.json
  browser-test/mobile-phone-change.test.js
  browser-test/mobile-verfication.test.js
  client/app.js
  client/components/footer/__snapshots__/footer.test.js.snap
  client/components/header/__snapshots__/header.test.js.snap
  client/components/login/__snapshots__/login.test.js.snap
  client/components/logout/__snapshots__/logout.test.js.snap
  client/components/logout/logout.js
  client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap
  client/components/mobile-phone-change/mobile-phone-change.test.js
  client/components/modal/__snapshots__/modal.test.js.snap
  client/components/modal/modal.js
  client/components/organization-wrapper/__snapshots__/organization-wrapper.test.js.snap
  client/components/organization-wrapper/organization-wrapper.js
  client/components/password-change/__snapshots__/password-change.test.js.snap
  client/components/password-confirm/__snapshots__/password-confirm.test.js.snap
  client/components/payment-process/payment-process.js
  client/components/payment-process/payment-process.test.js
  client/components/payment-status/__snapshots__/payment-status.test.js.snap
  client/components/registration/__snapshots__/registration.test.js.snap
  client/components/registration/registration.js
  client/components/registration/registration.test.js
  client/components/status/status.js
  client/components/status/status.test.js
  client/reducers/internet-mode.js
  client/reducers/language.js
  client/reducers/organization.js
  client/reducers/plan-exhausted.js
  client/utils/with-route-props.js
  config/jest.config.js
  package.json
  server/index.js
  server/routes/account.js
  yarn.lock
Labels: dependencies
